select
    h.market_id,
    h.outcome_index,
    h.clob_token_id,
    t.question,
    t.outcome_label,
    t.event_slug,
    t.market_slug,
    t.condition_id,
    t.sports_market_type,
    t.game_start_time,
    t.group_item_title,
    t.tags,
    t.clob_token_ids,
    t.is_active,
    t.is_closed,
    t.is_resolved,
    t.winning_outcome,
    t.winning_clob_token_id,
    t.market_volume_usd,
    h.odds_hour_utc,
    h.odds_hour_epoch,
    h.open_price,
    h.high_price,
    h.low_price,
    h.close_price,
    h.avg_price,
    h.observed_points,
    h.first_timestamp,
    h.first_observed_at,
    h.last_timestamp,
    h.last_observed_at
from {{ ref('selected_token_hourly_odds') }} as h
inner join {{ ref('wc2026_market_tokens') }} as t
    on h.clob_token_id = t.clob_token_id
