"""Polymarket market-scope presets, discovery, registry refresh, and SQL filters."""

from __future__ import annotations

from oddsfox_pipeline.ingestion.polymarket.scope_sql import (
    DEFAULT_MARKET_SCOPE,
    MARKET_SCOPE_ALL,
    market_scope_predicate_sql,
    market_scope_sql,
    validate_market_scope,
    validate_market_scopes,
)

from .config import (
    MarketScopeConfig,
    default_market_scopes_seed_path,
    load_market_scope_config,
    scope_config_hash,
)
from .gamma import (
    _chunk_market_ids,
    _fetch_markets_batch_resilient,
    _gamma_market_ids,
    _is_gamma_market_id,
)
from .predicates import (
    MarketScopeEventsScanResult,
    ResolvedMarketScopeDiscovery,
    _crawl_tag_allowed,
    _event_tag_slugs,
    _filter_crawl_tag_slugs,
    _parse_tag_discovery_keywords,
    _resolve_keyset_closed,
    _resolve_keyset_related_tags,
    _resolve_keyset_volume_min,
    event_in_scope,
    event_matches_scope_config,
    event_matches_scope_tags,
    is_market_scope_row,
    resolve_keyset_crawl_tags,
    resolve_keyset_tag_slugs,
    resolve_market_scope_discovery,
)
from .registry import (
    collect_scope_markets_from_events,
    refresh_registry_and_collect_markets_from_events,
    refresh_registry_and_collect_markets_targeted,
    refresh_registry_from_events,
)
from .scan import (
    DEFAULT_MAX_PAGES_WITHOUT_PROGRESS,
    DISCOVERY_MODE_FULL_KEYSET,
    DISCOVERY_MODE_TARGETED,
    DiscoveryMode,
    _collect_from_events,
    _collect_from_market_payloads,
    _empty_scan_result,
    _iter_market_scope_gamma_events,
    _merge_scan_results,
    _scan_market_scope_gamma_events,
    _scan_market_scope_gamma_events_keyset_pass,
)

__all__ = [
    "DEFAULT_MARKET_SCOPE",
    "DEFAULT_MAX_PAGES_WITHOUT_PROGRESS",
    "DISCOVERY_MODE_FULL_KEYSET",
    "DISCOVERY_MODE_TARGETED",
    "DiscoveryMode",
    "MARKET_SCOPE_ALL",
    "MarketScopeConfig",
    "MarketScopeEventsScanResult",
    "ResolvedMarketScopeDiscovery",
    "_chunk_market_ids",
    "_crawl_tag_allowed",
    "_collect_from_events",
    "_collect_from_market_payloads",
    "_empty_scan_result",
    "_event_tag_slugs",
    "_fetch_markets_batch_resilient",
    "_filter_crawl_tag_slugs",
    "_gamma_market_ids",
    "_is_gamma_market_id",
    "_iter_market_scope_gamma_events",
    "_merge_scan_results",
    "_parse_tag_discovery_keywords",
    "_resolve_keyset_closed",
    "_resolve_keyset_related_tags",
    "_resolve_keyset_volume_min",
    "_scan_market_scope_gamma_events",
    "_scan_market_scope_gamma_events_keyset_pass",
    "collect_scope_markets_from_events",
    "default_market_scopes_seed_path",
    "event_in_scope",
    "event_matches_scope_config",
    "event_matches_scope_tags",
    "is_market_scope_row",
    "load_market_scope_config",
    "market_scope_predicate_sql",
    "market_scope_sql",
    "refresh_registry_and_collect_markets_from_events",
    "refresh_registry_and_collect_markets_targeted",
    "refresh_registry_from_events",
    "resolve_market_scope_discovery",
    "resolve_keyset_crawl_tags",
    "resolve_keyset_tag_slugs",
    "scope_config_hash",
    "validate_market_scope",
    "validate_market_scopes",
]
