"""WC 2026 Polymarket market scope: registry refresh and strict SQL filters."""

from __future__ import annotations

from oddsfox.config.settings import (
    POLYMARKET_WC2026_KEYSET_CLOSED,
    POLYMARKET_WC2026_KEYSET_RELATED_TAGS,
    POLYMARKET_WC2026_KEYSET_VOLUME_MIN,
    POLYMARKET_WC2026_TAG_CLOSURE_KEYWORD_GATE,
    POLYMARKET_WC2026_TAG_CLOSURE_ROUNDS,
    POLYMARKET_WC2026_TAG_CRAWL_DENYLIST,
    POLYMARKET_WC2026_TAG_CRAWL_MAX,
    POLYMARKET_WC2026_TAG_DISCOVERY,
    POLYMARKET_WC2026_TAG_DISCOVERY_KEYWORDS,
)
from oddsfox.ingestion.polymarket.scope_sql import (
    MARKET_SCOPE_ALL,
    MARKET_SCOPE_WC2026,
    market_scope_predicate_sql,
    market_scope_sql,
    validate_market_scope,
)

from .config import (
    Wc2026ScopeConfig,
    default_wc2026_seed_path,
    load_wc2026_config,
    scope_config_hash,
)
from .gamma import (
    _chunk_market_ids,
    _fetch_markets_batch_resilient,
    _gamma_market_ids,
    _is_gamma_market_id,
)
from .predicates import (
    Wc2026EventsScanResult,
    _crawl_tag_allowed,
    _event_tag_slugs,
    _filter_crawl_tag_slugs,
    _parse_tag_discovery_keywords,
    _resolve_keyset_closed,
    _resolve_keyset_related_tags,
    _resolve_keyset_volume_min,
    event_in_scope,
    event_matches_wc2026_config,
    event_matches_wc2026_tags,
    is_wc2026_market_row,
    resolve_keyset_crawl_tags,
    resolve_keyset_tag_slugs,
)
from .registry import (
    collect_wc2026_markets_from_events,
    refresh_registry_and_collect_markets_from_events,
    refresh_registry_and_collect_markets_targeted,
    refresh_registry_from_events,
)
from .scan import (
    DEFAULT_MAX_PAGES_WITHOUT_PROGRESS,
    DISCOVERY_MODE_FULL_KEYSET,
    DISCOVERY_MODE_TARGETED,
    DiscoveryMode,
    _collect_from_events,
    _collect_from_market_payloads,
    _empty_scan_result,
    _iter_wc2026_gamma_events,
    _merge_scan_results,
    _scan_wc2026_gamma_events,
    _scan_wc2026_gamma_events_keyset_pass,
)

__all__ = [
    "DEFAULT_MAX_PAGES_WITHOUT_PROGRESS",
    "DISCOVERY_MODE_FULL_KEYSET",
    "DISCOVERY_MODE_TARGETED",
    "DiscoveryMode",
    "MARKET_SCOPE_ALL",
    "MARKET_SCOPE_WC2026",
    "POLYMARKET_WC2026_KEYSET_CLOSED",
    "POLYMARKET_WC2026_KEYSET_RELATED_TAGS",
    "POLYMARKET_WC2026_KEYSET_VOLUME_MIN",
    "POLYMARKET_WC2026_TAG_CLOSURE_KEYWORD_GATE",
    "POLYMARKET_WC2026_TAG_CLOSURE_ROUNDS",
    "POLYMARKET_WC2026_TAG_CRAWL_DENYLIST",
    "POLYMARKET_WC2026_TAG_CRAWL_MAX",
    "POLYMARKET_WC2026_TAG_DISCOVERY",
    "POLYMARKET_WC2026_TAG_DISCOVERY_KEYWORDS",
    "Wc2026EventsScanResult",
    "Wc2026ScopeConfig",
    "_chunk_market_ids",
    "_crawl_tag_allowed",
    "_collect_from_events",
    "_collect_from_market_payloads",
    "_empty_scan_result",
    "_event_tag_slugs",
    "_fetch_markets_batch_resilient",
    "_filter_crawl_tag_slugs",
    "_gamma_market_ids",
    "_is_gamma_market_id",
    "_iter_wc2026_gamma_events",
    "_merge_scan_results",
    "_parse_tag_discovery_keywords",
    "_resolve_keyset_closed",
    "_resolve_keyset_related_tags",
    "_resolve_keyset_volume_min",
    "_scan_wc2026_gamma_events",
    "_scan_wc2026_gamma_events_keyset_pass",
    "collect_wc2026_markets_from_events",
    "default_wc2026_seed_path",
    "event_in_scope",
    "event_matches_wc2026_config",
    "event_matches_wc2026_tags",
    "is_wc2026_market_row",
    "load_wc2026_config",
    "market_scope_predicate_sql",
    "market_scope_sql",
    "refresh_registry_and_collect_markets_from_events",
    "refresh_registry_and_collect_markets_targeted",
    "refresh_registry_from_events",
    "resolve_keyset_crawl_tags",
    "resolve_keyset_tag_slugs",
    "scope_config_hash",
    "validate_market_scope",
]
