-- costguard: disable-file=SQLCOST038
-- Hourly odds intentionally joins fact rows to unique market metadata on
-- market_ticker; odds_hour_epoch stays on the fact side and is not a dimension key.
select
    g.market_ticker,
    g.event_ticker,
    g.series_ticker,
    g.event_suffix,
    g.market_suffix,
    g.title,
    g.subtitle,
    g.yes_sub_title,
    g.no_sub_title,
    g.status,
    g.market_type,
    g.open_time,
    g.close_time,
    g.expiration_time,
    g.market_volume,
    g.open_interest,
    g.last_price,
    g.scraped_at,
    g.scope_name,
    g.team_name,
    g.group_letter,
    g.price_represents,
    g.canonical_team_name,
    g.tournament_status,
    g.is_still_alive,
    g.eliminated_stage_key,
    g.eliminated_match_date,
    g.next_match_date,
    g.next_stage_key,
    g.matches_played,
    g.wins,
    g.draws,
    g.losses,
    g.goals_for,
    g.goals_against,
    g.latest_completed_match_date,
    g.latest_completed_stage_key,
    g.market_status,
    g.is_live_market,
    g.source_state_anomaly,
    h.odds_hour_utc,
    h.odds_hour_epoch,
    h.open_price,
    h.high_price,
    h.low_price,
    h.close_price,
    h.avg_price,
    h.volume,
    h.latest_refreshed_at
from {{ ref('int_kalshi_wc2026_market_hourly_odds') }} as h
inner join {{ ref('int_kalshi_wc2026_group_winner_classification') }} as g
    on h.market_ticker = g.market_ticker
