"""Polymarket / HTTP tuning and scope env vars."""

from __future__ import annotations

import os

from oddsfox_pipeline.config._env import (
    _env_bool,
    _env_float,
    _env_int,
    _optional_env_int,
)

GAMMA_API_URL = "https://gamma-api.polymarket.com"
CLOB_API_URL = "https://clob.polymarket.com"
PMXT_API_URL = "https://api.pmxt.dev"
PMXT_API_KEY = os.getenv("PMXT_API_KEY", "").strip()

POLYGON_RPC_URL = os.getenv("POLYGON_RPC_URL", "").strip()
POLYGON_RPC_PROVIDER_LABEL = os.getenv("POLYGON_RPC_PROVIDER_LABEL", "").strip()
POLYGON_VERIFY_RPC_URL = os.getenv("POLYGON_VERIFY_RPC_URL", "").strip()
POLYGON_VERIFY_RPC_PROVIDER_LABEL = os.getenv(
    "POLYGON_VERIFY_RPC_PROVIDER_LABEL", ""
).strip()

MARKETS_REQUESTS_PER_SECOND = _env_int("MARKETS_REQUESTS_PER_SECOND", 10)
ODDS_REQUESTS_PER_SECOND = _env_int("ODDS_REQUESTS_PER_SECOND", 40)
HTTP_CONNECT_TIMEOUT_SECONDS = _env_float("HTTP_CONNECT_TIMEOUT_SECONDS", 5.0)
HTTP_READ_TIMEOUT_SECONDS = _env_float("HTTP_READ_TIMEOUT_SECONDS", 60.0)
HTTP_REQUEST_TIMEOUT = (
    HTTP_CONNECT_TIMEOUT_SECONDS,
    HTTP_READ_TIMEOUT_SECONDS,
)

MIN_ODDS_FIDELITY_MINUTES = 1
DEFAULT_ODDS_FIDELITY_MINUTES = 1440
WC2026_CONTRACT_DEFAULTS = {
    "scope_name": "wc2026",
    "event_min_lifetime_volume_usd": 100_000.0,
    "hourly_window_hours": 720,
    # Inclusive tournament span for futures-market minute windows
    # (opening match day through final day; see data-contracts.md).
    "tournament_start_utc": "2026-06-11T00:00:00+00:00",
    "tournament_end_utc": "2026-07-19T23:59:59+00:00",
}
POLYMARKET_WC2026_EVENT_MIN_VOLUME_USD = float(
    WC2026_CONTRACT_DEFAULTS["event_min_lifetime_volume_usd"]
)
POLYMARKET_WC2026_HOURLY_WINDOW_HOURS = int(
    WC2026_CONTRACT_DEFAULTS["hourly_window_hours"]
)
POLYMARKET_WC2026_TOURNAMENT_START_UTC = str(
    WC2026_CONTRACT_DEFAULTS["tournament_start_utc"]
)
POLYMARKET_WC2026_TOURNAMENT_END_UTC = str(
    WC2026_CONTRACT_DEFAULTS["tournament_end_utc"]
)
DEFAULT_POLYMARKET_WC2026_MARKET_SCOPE = str(WC2026_CONTRACT_DEFAULTS["scope_name"])
POLYMARKET_WC2026_SCOPE_EVENT_SLUGS = os.getenv(
    "POLYMARKET_WC2026_SCOPE_EVENT_SLUGS",
    "",
).strip()
POLYMARKET_WC2026_SCOPE_EVENT_SLUG_PREFIXES = os.getenv(
    "POLYMARKET_WC2026_SCOPE_EVENT_SLUG_PREFIXES", ""
).strip()
POLYMARKET_WC2026_SCOPE_EVENT_TAGS = os.getenv(
    "POLYMARKET_WC2026_SCOPE_EVENT_TAGS",
    "",
).strip()
POLYMARKET_WC2026_SCOPE_MARKET_IDS = os.getenv(
    "POLYMARKET_WC2026_SCOPE_MARKET_IDS",
    "",
).strip()
POLYMARKET_WC2026_SCOPE_REGISTRY_MAX_EVENT_PAGES = _optional_env_int(
    "POLYMARKET_WC2026_SCOPE_REGISTRY_MAX_EVENT_PAGES"
)


def _parse_scope_keyset_closed_env() -> bool | None:
    """Default False (open only); empty/any/none omits closed on /events/keyset."""
    raw = os.getenv("POLYMARKET_WC2026_SCOPE_KEYSET_CLOSED")
    if raw is None:
        return False
    normalized = str(raw).strip().lower()
    if not normalized or normalized in {"any", "all", "none", "null"}:
        return None
    if normalized in {"false", "0", "open"}:
        return False
    if normalized in {"true", "1", "closed"}:
        return True
    return None


def _parse_scope_keyset_volume_min_env() -> float | None:
    """Default omits volume_min on /events/keyset; registry uses event catalog."""
    raw = os.getenv("POLYMARKET_WC2026_SCOPE_KEYSET_VOLUME_MIN")
    if raw is None:
        return None
    normalized = str(raw).strip().lower()
    if not normalized or normalized in {"none", "null"}:
        return None
    try:
        return float(normalized)
    except ValueError:
        return None


POLYMARKET_WC2026_SCOPE_KEYSET_VOLUME_MIN = _parse_scope_keyset_volume_min_env()
POLYMARKET_WC2026_SCOPE_KEYSET_CLOSED = _parse_scope_keyset_closed_env()
POLYMARKET_WC2026_SCOPE_KEYSET_RELATED_TAGS = _env_bool(
    "POLYMARKET_WC2026_SCOPE_KEYSET_RELATED_TAGS",
    True,
)
POLYMARKET_WC2026_SCOPE_TAG_DISCOVERY = _env_bool(
    "POLYMARKET_WC2026_SCOPE_TAG_DISCOVERY",
    True,
)
POLYMARKET_WC2026_SCOPE_TAG_DISCOVERY_KEYWORDS = os.getenv(
    "POLYMARKET_WC2026_SCOPE_TAG_DISCOVERY_KEYWORDS",
    "",
).strip()
POLYMARKET_WC2026_SCOPE_TAG_CLOSURE_ROUNDS = _env_int(
    "POLYMARKET_WC2026_SCOPE_TAG_CLOSURE_ROUNDS",
    2,
)
POLYMARKET_WC2026_SCOPE_TAG_CRAWL_MAX = _env_int(
    "POLYMARKET_WC2026_SCOPE_TAG_CRAWL_MAX",
    100,
)
POLYMARKET_WC2026_SCOPE_TAG_CLOSURE_KEYWORD_GATE = _env_bool(
    "POLYMARKET_WC2026_SCOPE_TAG_CLOSURE_KEYWORD_GATE",
    True,
)


def _parse_scope_tag_crawl_denylist() -> tuple[str, ...]:
    raw = os.getenv(
        "POLYMARKET_WC2026_SCOPE_TAG_CRAWL_DENYLIST",
        "",
    ).strip()
    if not raw:
        return ()
    return tuple(part.strip().lower() for part in raw.split(",") if part.strip())


POLYMARKET_WC2026_SCOPE_TAG_CRAWL_DENYLIST = _parse_scope_tag_crawl_denylist()

# Unified minute-odds backfill: when false, skip markets/event-catalog/registry
# assets and reuse the warehouse catalog from a prior refresh (restart Dagster
# after changing). Default true keeps first-run discovery exhaustive.
POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_CATALOG = _env_bool(
    "POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_CATALOG",
    True,
)
# When false, skip match-minute raw plus its Scraper reference inputs and
# reuse warehouse rows from a prior run (restart Dagster after changing).
POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_MATCH = _env_bool(
    "POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_MATCH",
    True,
)
# When false, skip futures-minute raw and reuse warehouse rows from a prior run
# (restart Dagster after changing). Both match and futures may be false for a
# dbt-only unified minute rebuild.
POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_FUTURES = _env_bool(
    "POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_FUTURES",
    True,
)

# Live smoke defaults (consumed only by polymarket_wc2026_minute_odds_live_smoke).
POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_FRACTION = _env_float(
    "POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_FRACTION",
    0.05,
)
POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_SEED = (
    os.getenv(
        "POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_SEED",
        "wc2026-minute-smoke-v1",
    ).strip()
    or "wc2026-minute-smoke-v1"
)
POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_FUTURES_WINDOW_HOURS = _env_int(
    "POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_FUTURES_WINDOW_HOURS",
    24,
)

POLYMARKET_SOCCER_DAILY_SCHEDULE_ENABLED = _env_bool(
    "POLYMARKET_SOCCER_DAILY_SCHEDULE_ENABLED",
    False,
)
POLYMARKET_SOCCER_MONITOR_MAX_SUCCESS_AGE_HOURS = _env_int(
    "POLYMARKET_SOCCER_MONITOR_MAX_SUCCESS_AGE_HOURS", 30
)
POLYMARKET_SOCCER_MONITOR_STALE_RUN_HOURS = _env_int(
    "POLYMARKET_SOCCER_MONITOR_STALE_RUN_HOURS", 6
)
POLYMARKET_SOCCER_MONITOR_RETRY_WARN_HOURS = _env_int(
    "POLYMARKET_SOCCER_MONITOR_RETRY_WARN_HOURS", 24
)
POLYMARKET_SOCCER_MONITOR_RETRY_CRITICAL_HOURS = _env_int(
    "POLYMARKET_SOCCER_MONITOR_RETRY_CRITICAL_HOURS", 72
)
POLYMARKET_SOCCER_MONITOR_COMPLETION_GRACE_MINUTES = _env_int(
    "POLYMARKET_SOCCER_MONITOR_COMPLETION_GRACE_MINUTES", 60
)
POLYMARKET_SOCCER_MONITOR_COUNT_DROP_FRACTION = _env_float(
    "POLYMARKET_SOCCER_MONITOR_COUNT_DROP_FRACTION", 0.10
)
POLYMARKET_SOCCER_MONITOR_COVERAGE_DROP_POINTS = _env_float(
    "POLYMARKET_SOCCER_MONITOR_COVERAGE_DROP_POINTS", 5.0
)
POLYMARKET_SOCCER_MONITOR_REGRESSION_RATIO = _env_float(
    "POLYMARKET_SOCCER_MONITOR_REGRESSION_RATIO", 2.0
)
POLYMARKET_SOCCER_MONITOR_DISK_WARN_GIB = _env_float(
    "POLYMARKET_SOCCER_MONITOR_DISK_WARN_GIB", 10.0
)
POLYMARKET_SOCCER_MONITOR_DISK_CRITICAL_GIB = _env_float(
    "POLYMARKET_SOCCER_MONITOR_DISK_CRITICAL_GIB", 2.0
)
POLYMARKET_SOCCER_MONITOR_HISTORY_DAYS = _env_int(
    "POLYMARKET_SOCCER_MONITOR_HISTORY_DAYS", 400
)

__all__ = [
    "CLOB_API_URL",
    "GAMMA_API_URL",
    "HTTP_CONNECT_TIMEOUT_SECONDS",
    "HTTP_READ_TIMEOUT_SECONDS",
    "HTTP_REQUEST_TIMEOUT",
    "MARKETS_REQUESTS_PER_SECOND",
    "POLYMARKET_WC2026_HOURLY_WINDOW_HOURS",
    "POLYMARKET_WC2026_EVENT_MIN_VOLUME_USD",
    "POLYMARKET_WC2026_TOURNAMENT_END_UTC",
    "POLYMARKET_WC2026_TOURNAMENT_START_UTC",
    "POLYGON_RPC_PROVIDER_LABEL",
    "POLYGON_RPC_URL",
    "POLYGON_VERIFY_RPC_PROVIDER_LABEL",
    "POLYGON_VERIFY_RPC_URL",
    "DEFAULT_ODDS_FIDELITY_MINUTES",
    "DEFAULT_POLYMARKET_WC2026_MARKET_SCOPE",
    "MIN_ODDS_FIDELITY_MINUTES",
    "ODDS_REQUESTS_PER_SECOND",
    "PMXT_API_KEY",
    "PMXT_API_URL",
    "POLYMARKET_WC2026_SCOPE_EVENT_SLUG_PREFIXES",
    "POLYMARKET_WC2026_SCOPE_EVENT_SLUGS",
    "POLYMARKET_WC2026_SCOPE_EVENT_TAGS",
    "POLYMARKET_WC2026_SCOPE_KEYSET_CLOSED",
    "POLYMARKET_WC2026_SCOPE_KEYSET_RELATED_TAGS",
    "POLYMARKET_WC2026_SCOPE_KEYSET_VOLUME_MIN",
    "POLYMARKET_WC2026_SCOPE_MARKET_IDS",
    "POLYMARKET_WC2026_SCOPE_REGISTRY_MAX_EVENT_PAGES",
    "POLYMARKET_WC2026_SCOPE_TAG_DISCOVERY",
    "POLYMARKET_WC2026_SCOPE_TAG_DISCOVERY_KEYWORDS",
    "POLYMARKET_WC2026_SCOPE_TAG_CLOSURE_ROUNDS",
    "POLYMARKET_WC2026_SCOPE_TAG_CLOSURE_KEYWORD_GATE",
    "POLYMARKET_WC2026_SCOPE_TAG_CRAWL_DENYLIST",
    "POLYMARKET_WC2026_SCOPE_TAG_CRAWL_MAX",
    "POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_CATALOG",
    "POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_MATCH",
    "POLYMARKET_WC2026_MINUTE_ODDS_REFRESH_FUTURES",
    "POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_FRACTION",
    "POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_SEED",
    "POLYMARKET_WC2026_MINUTE_ODDS_SMOKE_FUTURES_WINDOW_HOURS",
    "POLYMARKET_SOCCER_DAILY_SCHEDULE_ENABLED",
    "POLYMARKET_SOCCER_MONITOR_COUNT_DROP_FRACTION",
    "POLYMARKET_SOCCER_MONITOR_COMPLETION_GRACE_MINUTES",
    "POLYMARKET_SOCCER_MONITOR_COVERAGE_DROP_POINTS",
    "POLYMARKET_SOCCER_MONITOR_DISK_CRITICAL_GIB",
    "POLYMARKET_SOCCER_MONITOR_DISK_WARN_GIB",
    "POLYMARKET_SOCCER_MONITOR_HISTORY_DAYS",
    "POLYMARKET_SOCCER_MONITOR_MAX_SUCCESS_AGE_HOURS",
    "POLYMARKET_SOCCER_MONITOR_REGRESSION_RATIO",
    "POLYMARKET_SOCCER_MONITOR_RETRY_CRITICAL_HOURS",
    "POLYMARKET_SOCCER_MONITOR_RETRY_WARN_HOURS",
    "POLYMARKET_SOCCER_MONITOR_STALE_RUN_HOURS",
    "WC2026_CONTRACT_DEFAULTS",
]
