select
    run_id,
    task_name,
    recorded_at,
    is_noop,
    duration_seconds,
    planned_tokens,
    processed_tokens,
    rows_fetched,
    windows_processed,
    empty_tokens,
    error_tokens,
    permanent_error_tokens,
    invalid_tokens,
    saved_rows,
    saved_daily_rows,
    sync_updates,
    queue_high_watermark,
    http_requests,
    http_429,
    http_errors,
    final_rps,
    token_rate,
    row_rate,
    market_tokens_distinct_tokens,
    odds_history_distinct_tokens,
    token_odds_daily_distinct_tokens,
    ledger_distinct_tokens,
    ledger_fully_checked_tokens,
    token_sync_skips_distinct_tokens,
    market_tokens_without_history,
    history_tokens_without_market_tokens,
    pre_clob_markets,
    invalid_tokens_from_planning,
    closed_done_tokens,
    persisted_skip_tokens,
    recent_skip_tokens,
    empty_cache_skip_tokens,
    already_current_tokens,
    duplicate_tokens,
    planned_vs_market_tokens_ratio,
    history_coverage_vs_market_tokens_ratio,
    daily_coverage_vs_market_tokens_ratio,
    ledger_coverage_vs_market_tokens_ratio,
    fully_checked_vs_market_tokens_ratio,
    case
        when coalesce(processed_tokens, 0) = 0 then null
        else rows_fetched::double / processed_tokens
    end as rows_per_processed_token
from {{ ref('stg_wc2026_polymarket_pipeline_run_events') }}
where task_name in ('sync_odds', 'reconcile_odds_ledger')
