select
    id as market_id,
    question,
    category,
    description,
    outcomes,
    volume,
    cast(active as boolean) as is_active,
    cast(closed as boolean) as is_closed,
    created_at,
    scraped_at,
    end_date,
    slug,
    event_slug,
    event_id,
    condition_id,
    sports_market_type,
    game_start_time,
    group_item_title,
    tags,
    clob_token_ids,
    cast(is_resolved as boolean) as is_resolved,
    winning_outcome,
    winning_clob_token_id
from {{ source('wc2026_polymarket_raw', 'markets') }}
