-- costguard: disable-file=SQLCOST038
-- Hourly odds intentionally joins fact rows to unique token metadata on
-- clob_token_id; odds_hour_epoch stays on the fact side and is not a dimension key.
select
    k.market_id,
    k.outcome_index,
    k.clob_token_id,
    k.question,
    k.source_outcome_label,
    k.event_slug,
    k.market_slug,
    k.condition_id,
    k.sports_market_type,
    k.game_start_time,
    k.group_item_title,
    k.tags,
    k.clob_token_ids,
    k.is_active,
    k.is_closed,
    k.is_resolved,
    k.market_status,
    k.is_live_market,
    k.is_active_team_live_market,
    k.source_state_anomaly,
    k.winning_outcome,
    k.winning_clob_token_id,
    k.market_volume_usd,
    k.stage_key,
    k.stage_rank,
    k.market_direction,
    k.price_represents,
    k.progression_outcome_label,
    k.team_name,
    k.canonical_team_name,
    k.tournament_status,
    k.is_still_alive,
    k.eliminated_stage_key,
    k.eliminated_match_date,
    k.next_match_date,
    k.next_stage_key,
    k.matches_played,
    k.wins,
    k.draws,
    k.losses,
    k.goals_for,
    k.goals_against,
    k.latest_completed_match_date,
    k.latest_completed_stage_key,
    h.odds_hour_utc,
    h.odds_hour_epoch,
    h.open_price,
    h.high_price,
    h.low_price,
    h.close_price,
    h.avg_price,
    h.observed_points,
    h.first_timestamp,
    h.first_observed_at,
    h.last_timestamp,
    h.last_observed_at
from {{ ref('int_polymarket_wc2026_token_hourly_odds') }} as h
inner join {{ ref('polymarket_wc2026_knockout_market_tokens') }} as k
    on h.clob_token_id = k.clob_token_id
