with latest_payloads as (
    select
        market_id,
        question,
        category,
        description,
        market_resolution_source,
        outcomes,
        volume,
        active,
        closed,
        created_at,
        scraped_at,
        end_date,
        slug,
        event_slug,
        event_id,
        event_title,
        event_start_time,
        event_finished_time,
        event_game_id,
        event_ended,
        condition_id,
        sports_market_type,
        game_start_time,
        group_item_title,
        group_item_threshold,
        line,
        tags,
        clob_token_ids,
        is_resolved,
        winning_outcome,
        winning_clob_token_id
    from {{ source('polymarket_wc2026_raw', 'event_market_payload_snapshots') }}
    qualify row_number() over (
        partition by market_id
        order by observed_at desc
    ) = 1
)

select
    market_id,
    question,
    category,
    description,
    market_resolution_source,
    outcomes,
    volume,
    cast(active as boolean) as is_active,
    cast(closed as boolean) as is_closed,
    created_at,
    scraped_at,
    end_date,
    slug,
    event_slug,
    event_id,
    event_title,
    event_start_time,
    event_finished_time,
    event_game_id,
    cast(event_ended as boolean) as event_ended,
    condition_id,
    sports_market_type,
    game_start_time,
    group_item_title,
    group_item_threshold,
    line,
    tags,
    clob_token_ids,
    cast(is_resolved as boolean) as is_resolved,
    winning_outcome,
    winning_clob_token_id
from latest_payloads
